//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_AccessEventLog
    {
        public System.Guid SEQ { get; set; }
        public string AccessUserCard_SID { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
        public string MainControllerId { get; set; }
        public string MainControllerName { get; set; }
        public string ControllerNo { get; set; }
        public string ControllerName { get; set; }
        public string ConsoleNo { get; set; }
        public string ConsoleName { get; set; }
        public Nullable<int> DoorNo { get; set; }
        public Nullable<int> RESULT { get; set; }
        public string DoorName { get; set; }
        public string CompanyName { get; set; }
        public string USERID { get; set; }
        public string USERNAME { get; set; }
        public string CARDDATA { get; set; }
        public string EXTENSIONDATA { get; set; }
        public Nullable<int> ACCESS_TYPE { get; set; }
        public string CCServerID { get; set; }
        public Nullable<int> FailureCode { get; set; }
        public string OrganizationId { get; set; }
        public string Organization { get; set; }
        public string MemberID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Door_DID { get; set; }
        public string Site_SID { get; set; }
        public string ControllerID { get; set; }
        public string ConsoleID { get; set; }
    }
}
