//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class OC_OutputportInfo
    {
        public string DID { get; set; }
        public Nullable<bool> ParentType { get; set; }
        public Nullable<int> Output_No { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<int> Output_Type { get; set; }
        public string Siren_Partition_No { get; set; }
        public string ParentID { get; set; }
        public string ModiyfyBy { get; set; }
        public System.DateTime ModiyfyDate { get; set; }
        public string ModiyfyIP { get; set; }
        public string Remark { get; set; }
        public bool IsSecureSafety { get; set; }
        public Nullable<bool> IsAlwaysCloseWhenArm { get; set; }
        public Nullable<bool> IsAlwaysOpenWhenDisArm { get; set; }
        public Nullable<bool> IsHighPass { get; set; }
        public Nullable<bool> IsReportLockState { get; set; }
        public Nullable<int> Floor { get; set; }
    }
}
