//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ADTSC20 : DbContext
    {
        public ADTSC20()
            : base("name=ADTSC20")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CM_AccessEventLog> CM_AccessEventLog { get; set; }
        public virtual DbSet<CM_User> CM_User { get; set; }
        public virtual DbSet<OC_OutputportInfo> OC_OutputportInfo { get; set; }
        public virtual DbSet<UC_Organization> UC_Organization { get; set; }
    }
}
