//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class UC_Organization
    {
        public string SID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedIP { get; set; }
        public string ModiyfyBy { get; set; }
        public System.DateTime ModiyfyDate { get; set; }
        public string ModiyfyIP { get; set; }
        public bool IsDelete { get; set; }
        public string Remark { get; set; }
        public string Parent_SID { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationCategory { get; set; }
        public string SITE_SID { get; set; }
    }
}
